export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const SIGNIN = "SIGNIN"
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNIN_FAILURE = "SIGNIN_FAILURE"

export const SIGNUP = "SIGNUP"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"

export const COMPLETE_PROFILE = "COMPLETE_PROFILE"
export const COMPLETE_PROFILE_SUCCESS = "COMPLETE_PROFILE_SUCCESS"
export const COMPLETE_PROFILE_FAILURE = "COMPLETE_PROFILE_FAILURE"

export const LOGOUT = "LOGOUT"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"


export const SHIFT_ONE_STATUS = 'SHIFT_ONE_STATUS'

export const SHIFT_TWO_STATUS = 'SHIFT_TWO_STATUS'

export const CURRENT_DATE = 'CURRENT_DATE'


export const ADD_VENDOR = "ADD_VENDOR"
export const ADD_VENDOR_SUCCESS = "ADD_VENDOR_SUCCESS"
export const ADD_VENDOR_FAILURE = "ADD_VENDOR_FAILURE"


export const GET_VENDOR = "GET_VENDOR"
export const GET_VENDOR_SUCCESS = "GET_VENDOR_SUCCESS"
export const GET_VENDOR_FAILURE = "GET_VENDOR_FAILURE"

export const POST_SHIFT_START = "POST_SHIFT_START"
export const POST_SHIFT_START_SUCCESS = "POST_SHIFT_START_SUCCESS"
export const POST_SHIFT_START_FAILURE = "POST_SHIFT_START_FAILURE"

export const POST_SHIFT_END = "POST_SHIFT_END"
export const POST_SHIFT_END_SUCCESS = "POST_SHIFT_END_SUCCESS"
export const POST_SHIFT_END_FAILURE = "POST_SHIFT_END_FAILURE"


export const SET_CURRENT_RATES = "SET_CURRENT_RATES"
export const SET_CURRENT_RATES_SUCCESS = "SET_CURRENT_RATES_SUCCESS"
export const SET_CURRENT_RATES_FAILURE = "SET_CURRENT_RATES_FAILURE"


export const GET_CURRENT_RATES = "GET_CURRENT_RATES"
export const GET_CURRENT_RATES_SUCCESS = "GET_CURRENT_RATES_SUCCESS"
export const GET_CURRENT_RATES_FAILURE = "GET_CURRENT_RATES_FAILURE"


