export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const SIGNIN = "SIGNIN"
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNIN_FAILURE = "SIGNIN_FAILURE"

export const SIGNUP = "SIGNUP"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"

export const COMPLETE_PROFILE = "COMPLETE_PROFILE"
export const COMPLETE_PROFILE_SUCCESS = "COMPLETE_PROFILE_SUCCESS"
export const COMPLETE_PROFILE_FAILURE = "COMPLETE_PROFILE_FAILURE"

export const LOGOUT = "LOGOUT"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"


export const SHIFT_ONE_STATUS = 'SHIFT_ONE_STATUS'

export const SHIFT_TWO_STATUS = 'SHIFT_TWO_STATUS'

export const CURRENT_DATE = 'CURRENT_DATE'